# Generated by Django 5.1.5 on 2025-06-01 16:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Difficulties',
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='GuidePics/')),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(message='Invalid phone number format!', regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(message='Invalid phone number format!', regex='^\\+?1?\\d{9,15}$')])),
                ('newsletter', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AdventureApp.difficulty')),
                ('tags', models.ManyToManyField(to='AdventureApp.tag')),
            ],
        ),
        migrations.CreateModel(
            name='TripGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='TripImages/')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdventureApp.trip')),
            ],
            options={
                'verbose_name_plural': 'Media files',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('maxattendants', models.IntegerField()),
                ('attendants', models.ManyToManyField(blank=True, related_name='schedules', to=settings.AUTH_USER_MODEL)),
                ('guides', models.ManyToManyField(to='AdventureApp.guide')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdventureApp.trip')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('start__lte', models.F('end'))), name='starts_earlier_than_finishes')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('revtitle', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('revtrip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AdventureApp.trip')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('customer', 'revtrip'), name='unique_rating')],
            },
        ),
    ]
