# Generated by Django 5.1.5 on 2025-06-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdventureApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='fullname',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
