# Generated by Django 5.1.5 on 2025-05-08 14:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdventureApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='difficulty',
            options={'verbose_name_plural': 'Difficulties'},
        ),
        migrations.AlterModelOptions(
            name='tripgallery',
            options={'verbose_name_plural': 'Media files'},
        ),
        migrations.AddField(
            model_name='review',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='date_edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tripgallery',
            name='picture',
            field=models.ImageField(upload_to='TripImages/'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('customer', 'revtrip'), name='unique_rating'),
        ),
    ]
