# Generated by Django 5.1.5 on 2025-06-02 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdventureApp', '0002_customer_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='fullname',
        ),
    ]
