# Generated by Django 5.1.5 on 2025-05-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdventureApp', '0002_alter_difficulty_options_alter_tripgallery_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='portrait',
            field=models.ImageField(blank=True, null=True, upload_to='GuidePics/'),
        ),
    ]
