# Generated by Django 5.1.5 on 2025-05-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdventureApp', '0003_guide_portrait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='phone',
            field=models.CharField(max_length=32),
        ),
    ]
