# Generated by Django 5.1.5 on 2025-05-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdventureApp', '0005_alter_customer_options_alter_customer_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='attendants',
            field=models.ManyToManyField(blank=True, null=True, to='AdventureApp.customer'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.CheckConstraint(condition=models.Q(('start__lte', models.F('end'))), name='starts_earlier_than_finishes'),
        ),
    ]
