# Generated by Django 5.1.5 on 2025-05-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdventureApp', '0006_alter_schedule_attendants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='description',
            field=models.TextField(default='Sample description'),
            preserve_default=False,
        ),
    ]
