# Generated by Django 5.1.5 on 2025-05-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdventureApp', '0007_guide_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='newsletter',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
