# Generated by Django 5.1.5 on 2025-05-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdventureApp', '0008_customer_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='attendants',
            field=models.ManyToManyField(blank=True, to='AdventureApp.customer'),
        ),
    ]
