# Generated by Django 5.1.5 on 2025-05-28 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdventureApp', '0009_alter_schedule_attendants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='phone',
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(message='Invalid phone number format!', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
