# Generated by Django 5.1.5 on 2025-05-28 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdventureApp', '0010_remove_guide_phone_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='phone',
            field=models.CharField(default='+000000000000', max_length=32, validators=[django.core.validators.RegexValidator(message='Invalid phone number format!', regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
    ]
